<a href="https://colab.research.google.com/github/jucorreab/Algoritmo-Exercicios/blob/main/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

M = np.array([
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]
])

autovalores, autovetores = np.linalg.eig(M)

D = np.diag(autovalores)
A = autovetores

V_diag = A @ D @ np.linalg.inv(A)

print("Matriz Original A:\n", M)
print("\nAutovalores:\n", np.round(autovalores, 2))
print("\nAutovetores (Matriz A):\n", np.round(P, 2))
print("\nMatriz Diagonal D:\n", np.round(D, 2))
print("\nVerificação (V ≈ A * D * A^-1):\n", np.round(V_diag).astype(int))

Matriz Original A:
 [[5 4 2 1]
 [4 5 3 2]
 [2 3 5 4]
 [1 2 4 5]]

Autovalores:
 [13.08  5.24  0.92  0.76]

Autovetores (Matriz A):
 [[ 0.46  0.6   0.54 -0.37]
 [ 0.54  0.37 -0.46  0.6 ]
 [ 0.54 -0.37 -0.46 -0.6 ]
 [ 0.46 -0.6   0.54  0.37]]

Matriz Diagonal D:
 [[13.08  0.    0.    0.  ]
 [ 0.    5.24  0.    0.  ]
 [ 0.    0.    0.92  0.  ]
 [ 0.    0.    0.    0.76]]

Verificação (V ≈ A * D * A^-1):
 [[5 4 2 1]
 [4 5 3 2]
 [2 3 5 4]
 [1 2 4 5]]
