<a href="https://colab.research.google.com/github/jucorreab/Algoritmo-Exercicios/blob/main/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

M = np.array([
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]
])

autovalores, autovetores = np.linalg.eig(M)

D = np.diag(autovalores)
A = autovetores

V_diag = A @ D @ np.linalg.inv(A)

print("Matriz Original M:\n", M)
print("\nAutovalores:\n", np.round(autovalores, 2))
print("\nAutovetores (Matriz A):\n", np.round(A, 2))
print("\nMatriz Diagonal D:\n", np.round(D, 2))
print("\nVerificação (V ≈ A * D * A^-1):\n", np.round(V_diag).astype(int))

Matriz Original M:
 [[5 4 2 1]
 [4 5 3 2]
 [2 3 5 4]
 [1 2 4 5]]

Autovalores:
 [13.1 5.2 0.9 0.8]

Autovetores (Matriz A):
 [[0.5 0.6 0.5 -0.4]
 [0.5 0.4 -0.5 0.6]
 [0.5 -0.4 -0.5 -0.6]
 [0.5 -0.6 0.5 0.4]]

Matriz Diagonal D:
 [[13.1 0.0 0.0 0.0]
 [0.0 5.2 0.0 0.0]
 [0.0 0.0 0.9 0.0]
 [0.0 0.0 0.0 0.8]]

Verificação (V ≈ A * D * A^-1):
 [[5 4 2 1]
 [4 5 3 2]
 [2 3 5 4]
 [1 2 4 5]]
