<a href="https://colab.research.google.com/github/jucorreab/Algoritmo-Exercicios/blob/main/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

M = np.array([
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]
])

autovalores, autovetores = np.linalg.eig(M)

D = np.diag(autovalores)
A = autovetores

V_diag = A @ D @ np.linalg.inv(A)

print("Matriz Original M:\n", M)
print("\nAutovalores:\n", np.round(autovalores, 2))
print("\nAutovetores (Matriz A):\n", np.round(A, 2))
print("\nMatriz Diagonal D:\n", np.round(D, 2))
print("\nVerificação (V ≈ A * D * A^-1):\n", np.round(V_diag).astype(int))

Matriz Original M:
 [[5 4 2 1]
 [4 5 3 2]
 [2 3 5 4]
 [1 2 4 5]]

Autovalores:
 [13.08  5.24  0.92  0.76]

Autovetores (Matriz A):
 [[ 0.46  0.6   0.54 -0.37]
 [ 0.54  0.37 -0.46  0.6 ]
 [ 0.54 -0.37 -0.46 -0.6 ]
 [ 0.46 -0.6   0.54  0.37]]

Matriz Diagonal D:
 [[13.08  0.    0.    0.  ]
 [ 0.    5.24  0.    0.  ]
 [ 0.    0.    0.92  0.  ]
 [ 0.    0.    0.    0.76]]

Verificação (V ≈ A * D * A^-1):
 [[5 4 2 1]
 [4 5 3 2]
 [2 3 5 4]
 [1 2 4 5]]


In [52]:
import numpy as np

def determinante_4x4(m):
    def submatriz(m, row, col):
        return [
            [m[i][j] for j in range(4) if j != col]
            for i in range(4) if i != row
        ]

    det = 0
    for col in range(4):
        sub_det = determinante_3x3(submatriz(m, 0, col))
        det += ((-1) ** col) * m[0][col] * sub_det

    return det

def determinante_3x3(m):
    return (
        m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1]) -
        m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0]) +
        m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0])
    )

def encontrar_autovalores_e_autovetores(m):
    matriz = np.array(m, dtype=float)
    autovalores = []
    autovetores = []

    for _ in range(4):
        v = np.random.rand(4)
        v /= np.linalg.norm(v)

        autovalor_anterior = 0
        for _ in range(100):
            v = np.dot(matriz, v)
            v /= np.linalg.norm(v)
            autovalor_atual = np.dot(v, np.dot(matriz, v))

            if abs(autovalor_atual - autovalor_anterior) < 1e-9:
                break

            autovalor_anterior = autovalor_atual

        autovalores.append(autovalor_atual)
        autovetores.append(v)

        matriz = matriz - autovalor_atual * np.outer(v, v)

    return autovalores, autovetores

def diagonalizar_matriz(m):
    autovalores, autovetores = encontrar_autovalores_e_autovetores(m)
    D = np.diag(autovalores)
    P = np.column_stack(autovetores)
    return D, P

def verificar_diagonalizacao_frobenius(A, D, P):
    P_inv = np.linalg.inv(P)
    A_reconstituida = np.dot(np.dot(P, D), P_inv)
    return np.linalg.norm(A - A_reconstituida, 'fro') < 1e-6

def exibir_resultados(m):
    print("Matriz original:")
    for linha in m:
        print(linha)

    autovalores, autovetores = encontrar_autovalores_e_autovetores(m)
    print("\nAutovalores:")
    print(np.round(autovalores, 2))

    print("\nAutovetores:")
    for autovetor in autovetores:
        print(np.round(autovetor, 2))

    D, P = diagonalizar_matriz(m)
    print("\nMatriz diagonal (D):")
    print(np.round(D, 2))

    print("\nMatriz de autovetores (P):")
    print(np.round(P, 2))

    if verificar_diagonalizacao_frobenius(np.array(m, dtype=float), D, P):
        print("\nA matriz foi diagonalizada corretamente: A = P * D * P^-1")
    else:
        print("\nA matriz não foi diagonalizada corretamente.")

matriz_exemplo = [
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]

]

exibir_resultados(matriz_exemplo)


Matriz original:
[5, 4, 2, 1]
[4, 5, 3, 2]
[2, 3, 5, 4]
[1, 2, 4, 5]

Autovalores:
[13.08  5.24  0.92  0.76]

Autovetores:
[0.46 0.54 0.54 0.46]
[ 0.6   0.37 -0.37 -0.6 ]
[ 0.54 -0.46 -0.46  0.54]
[-0.37  0.6  -0.6   0.37]

Matriz diagonal (D):
[[13.08  0.    0.    0.  ]
 [ 0.    5.24  0.    0.  ]
 [ 0.    0.    0.92  0.  ]
 [ 0.    0.    0.    0.76]]

Matriz de autovetores (P):
[[ 0.46  0.6   0.54 -0.37]
 [ 0.54  0.37 -0.46  0.6 ]
 [ 0.54 -0.37 -0.46 -0.6 ]
 [ 0.46 -0.6   0.54  0.37]]

A matriz não foi diagonalizada corretamente.


In [39]:
# Função para calcular a norma de um vetor
def vector_norm(v):
    return sum(x**2 for x in v)**0.5

# Função para multiplicar uma matriz por um vetor
def matrix_vector_multiply(matrix, vector):
    result = [sum(matrix[i][j] * vector[j] for j in range(len(matrix))) for i in range(len(matrix))]
    return result

# Função para realizar o método de potência para encontrar o autovalor dominante
def power_method(matrix, num_iterations=1000, tolerance=1e-6):
    n = len(matrix)

    vector = [1] * n
    for _ in range(num_iterations):
        new_vector = matrix_vector_multiply(matrix, vector)

        norm = vector_norm(new_vector)

        new_vector = [x / norm for x in new_vector]

        if all(abs(new_vector[i] - vector[i]) < tolerance for i in range(n)):
            break

        vector = new_vector

    eigenvalue = sum(new_vector[i] * matrix_vector_multiply(matrix, new_vector)[i] for i in range(n))
    return eigenvalue, new_vector

# Função para encontrar todos os autovalores e autovetores de uma matriz
def find_all_eigenvalues_and_eigenvectors(matrix):
    eigenvalues = []
    eigenvectors = []
    n = len(matrix)

    for _ in range(n):
        eigenvalue, eigenvector = power_method(matrix)
        eigenvalues.append(eigenvalue)
        eigenvectors.append(eigenvector)

        # Atualiza a matriz subtraindo o autovalor encontrado vezes a identidade
        matrix = [[matrix[i][j] - eigenvalue if i == j else matrix[i][j] for j in range(n)] for i in range(n)]

    return eigenvalues, eigenvectors

# Função para diagonalizar a matriz
def diagonalize_matrix(matrix):
    eigenvalues, eigenvectors = find_all_eigenvalues_and_eigenvectors(matrix)

    # Construir a matriz diagonal D
    D = [[eigenvalues[i] if i == j else 0 for j in range(len(eigenvalues))] for i in range(len(eigenvalues))]

    # Construir a matriz P (autovetores)
    P = [[eigenvectors[i][j] for i in range(len(eigenvectors))] for j in range(len(eigenvectors))]

    # Calcular a inversa de P
    P_inv = matrix_inverse(P)

    # Reconstruir a matriz original
    reconstructed_matrix = matrix_multiply(matrix_multiply(P, D), P_inv)

    return eigenvalues, eigenvectors, D, reconstructed_matrix

# Função para calcular a inversa de uma matriz 4x4
def matrix_inverse(matrix):
    n = len(matrix)
    identity = [[1 if i == j else 0 for j in range(n)] for i in range(n)]

    for i in range(n):
        factor = matrix[i][i]
        for j in range(n):
            matrix[i][j] /= factor
            identity[i][j] /= factor
        for k in range(n):
            if k != i:
                factor = matrix[k][i]
                for j in range(n):
                    matrix[k][j] -= factor * matrix[i][j]
                    identity[k][j] -= factor * identity[i][j]

    # Retorna a inversa da matriz
    return identity

# Função para multiplicar duas matrizes
def matrix_multiply(A, B):
    n = len(A)
    result = [[sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
    return result

# Matriz de exemplo
matrix = [
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]
]

# Diagonalizando a matriz
eigenvalues, eigenvectors, diagonal_matrix, reconstructed_matrix = diagonalize_matrix(matrix)

# Exibindo os resultados
print("Matriz Original:")
for row in matrix:
    print(row)

print("\nAutovalores:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

print("\nAutovetores:")
for vector in eigenvectors:
    print(vector)

print("\nMatriz Diagonal:")
for row in diagonal_matrix:
    print(row)

print("\nReconstrução da Matriz Original (P * D * P^-1):")
for row in reconstructed_matrix:
    print(row)


ZeroDivisionError: float division by zero

def calcular_determinante(matriz):
  """Calcula o determinante de uma matriz utilizando a expansão de Laplace.

  Args:
    matriz: Uma lista de listas representando a matriz.

  Returns:
    O determinante da matriz.
  """

  if len(matriz) == 1:
    return matriz[0][0]
  elif len(matriz) == 2:
    return matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0]
  else:
    determinante = 0
    for j in range(len(matriz)):
      cofactor = (-1) ** (1 + j) * calcular_determinante([row[:j] + row[j+1:] for row in matriz[1:]])
      determinante += matriz[0][j] * cofactor
    return determinante

def polinomio_caracteristico(matriz):
  """Calcula o polinômio característico de uma matriz.

  Args:
    matriz: Uma lista de listas representando a matriz.

  Returns:
    Uma string representando o polinômio característico.
  """

  n = len(matriz)
  polinomio = ""
  for i in range(n+1):
    submatriz = [[matriz[j][k] - (i-1) if j == k else matriz[j][k] for k in range(n)] for j in range(n)]
    det = calcular_determinante(submatriz)
    if det != 0:
      polinomio += f"{det}*λ^{n-i} + "
  return polinomio[:-3]  # Remove o último "+ "

# Matriz dada
A = [[5, 4, 2, 1],
     [4, 5, 3, 2],
     [2, 3, 5, 4],
     [1, 2, 4, 5]]

# Calcula o polinômio característico
resultado = polinomio_caracteristico(A)
print(resultado)

In [1]:
import math
import random  # Certifique-se de importar o módulo random

 # Função para obter a submatriz 3x3 ao remover uma linha e uma coluna de uma matriz 4x4
def submatriz(m, linha_remover, coluna_remover):
    return [
        [m[i][j] for j in range(4) if j != coluna_remover]
        for i in range(4) if i != linha_remover
    ]

# Função para calcular o determinante de uma matriz 3x3
def determinante_3x3(m):
    return (
        m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
        - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
        + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0])
    )

# Função para calcular a adjunta de uma matriz 4x4
def adjunta_4x4(m):
    adj = []
    for i in range(4):
        adj_linha = []
        for j in range(4):
            submat = submatriz(m, i, j)
            adj_linha.append(((-1)**(i+j)) * determinante_3x3(submat))
        adj.append(adj_linha)
    # Transpor a matriz adjunta
    return [[adj[j][i] for j in range(4)] for i in range(4)]

# Função para calcular a inversa de uma matriz 4x4
def inversa_4x4(m):
    det = (
        m[0][0] * determinante_3x3(submatriz(m, 0, 0))
        - m[0][1] * determinante_3x3(submatriz(m, 0, 1))
        + m[0][2] * determinante_3x3(submatriz(m, 0, 2))
        - m[0][3] * determinante_3x3(submatriz(m, 0, 3))
    )
    if det == 0:
        raise ValueError("Matriz não é inversível (determinante = 0)")
    adj = adjunta_4x4(m)
    return [[adj[i][j] / det for j in range(4)] for i in range(4)]

# Função para verificar a diagonalização com mensagens de debug
def verificar_diagonalizacao(A, D, P):
    print("\nVerificando diagonalização...")

    # Calcula P^-1
    try:
        P_inv = inversa_4x4(P)
    except ValueError as e:
        print(f"Erro ao calcular P^-1: {e}")
        return False

    # Reconstituir A
    A_reconstituida = multiplicar_matrizes(multiplicar_matrizes(P, D), P_inv)

    # Calcula o erro total
    erro = sum(
        abs(A[i][j] - A_reconstituida[i][j])
        for i in range(4)
        for j in range(4)
    )
    print(f"Erro total na reconstituição de A: {erro:.10f}")

    # Critério de validação
    tolerancia = 1e-4
    return erro < tolerancia

# Exibir resultados com mensagens de erro detalhadas
def exibir_resultados(m):
    print("\nMatriz original:")
    for linha in m:
        print(linha)

    autovalores, autovetores = calcular_autovalores_autovetores(m)
    print("\nAutovalores:")
    print(autovalores)
    print("\nAutovetores:")
    for linha in autovetores:
        print(linha)

    # Montar matriz diagonal e matriz de autovetores
    D = [[autovalores[i] if i == j else 0 for j in range(4)] for i in range(4)]
    P = [[autovetores[i][j] for j in range(4)] for i in range(4)]

    print("\nMatriz diagonal (D):")
    for linha in D:
        print(linha)

    print("\nMatriz de autovetores (P):")
    for linha in P:
        print(linha)

    if verificar_diagonalizacao(m, D, P):
        print("\nA matriz foi diagonalizada corretamente: A = P * D * P^-1")
    else:
        print("\nA matriz não foi diagonalizada corretamente.")

# Sua matriz de exemplo e função principal
matriz_exemplo = [
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]
]

exibir_resultados(matriz_exemplo)



Matriz original:
[5, 4, 2, 1]
[4, 5, 3, 2]
[2, 3, 5, 4]
[1, 2, 4, 5]


NameError: name 'calcular_autovalores_autovetores' is not defined

In [16]:
import math

def multiplicar_matrizes(A, B):
    return [
        [
            sum(A[i][k] * B[k][j] for k in range(len(B)))
            for j in range(len(B[0]))
        ]
        for i in range(len(A))
    ]

def transpor_matriz(m):
    return [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))]

def calcular_autovalores_e_autovetores(m):
    n = len(m)
    autovalores = []
    autovetores = []

    matriz_residual = [linha[:] for linha in m]

    for _ in range(n):
        v = [1.0] * n
        for _ in range(100):
            w = [sum(matriz_residual[i][j] * v[j] for j in range(n)) for i in range(n)]
            norma = math.sqrt(sum(x**2 for x in w))
            v = [x / norma for x in w]

        lambda_autovalor = sum(
            sum(matriz_residual[i][j] * v[j] for j in range(n)) * v[i] for i in range(n)
        )
        autovalores.append(lambda_autovalor)
        autovetores.append(v)

        for i in range(n):
            for j in range(n):
                matriz_residual[i][j] -= lambda_autovalor * v[i] * v[j]

    return autovalores, autovetores

def exibir_resultados(m):
    print("Matriz original:")
    for linha in m:
        print([round(x, 2) for x in linha])

    autovalores, autovetores = calcular_autovalores_e_autovetores(m)
    print("\nAutovalores:")
    print([round(x, 2) for x in autovalores])

    print("\nAutovetores:")
    for vetor in autovetores:
        print([round(x, 2) for x in vetor])

    D = [[0 if i != j else autovalores[i] for j in range(len(autovalores))] for i in range(len(autovalores))]
    print("\nMatriz diagonal (D):")
    for linha in D:
        print([round(x, 2) for x in linha])

    P = transpor_matriz(autovetores)
    print("\nMatriz de autovetores (P):")
    for linha in P:
        print([round(x, 2) for x in linha])

    P_inv = inversa_4x4(P)
    A_reconstituida = multiplicar_matrizes(multiplicar_matrizes(P, D), P_inv)

    print("\nVerificação (A reconstruída):")
    for linha in A_reconstituida:
      print([round(x) for x in linha])

def determinante_4x4(m):
    def determinante_3x3(m):
        return (m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
                - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
                + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]))

    det = 0
    for i in range(4):
        sub_matriz = [[m[j][k] for k in range(4) if k != i] for j in range(1, 4)]
        cofactor = (-1) ** i * m[0][i] * determinante_3x3(sub_matriz)
        det += cofactor
    return det

def adjunta_4x4(m):
    def determinante_3x3(m):
        return (m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
                - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
                + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]))

    adj = []
    for i in range(4):
        adj_linha = []
        for j in range(4):
            sub_matriz = [[m[y][x] for x in range(4) if x != j] for y in range(4) if y != i]
            cofactor = (-1) ** (i + j) * determinante_3x3(sub_matriz)
            adj_linha.append(cofactor)
        adj.append(adj_linha)
    return transpor_matriz(adj)

def inversa_4x4(m):
    det = determinante_4x4(m)
    adj = adjunta_4x4(m)
    return [[adj[i][j] / det for j in range(4)] for i in range(4)]

matriz_exemplo = [
    [5, 4, 2, 1],
    [4, 5, 3, 2],
    [2, 3, 5, 4],
    [1, 2, 4, 5]
]

exibir_resultados(matriz_exemplo)

Matriz original:
[5, 4, 2, 1]
[4, 5, 3, 2]
[2, 3, 5, 4]
[1, 2, 4, 5]

Autovalores:
[13.08, 5.24, 0.92, 0.76]

Autovetores:
[0.46, 0.54, 0.54, 0.46]
[0.6, 0.37, -0.37, -0.6]
[0.54, -0.46, -0.46, 0.54]
[-0.37, 0.6, -0.6, 0.37]

Matriz diagonal (D):
[13.08, 0, 0, 0]
[0, 5.24, 0, 0]
[0, 0, 0.92, 0]
[0, 0, 0, 0.76]

Matriz de autovetores (P):
[0.46, 0.6, 0.54, -0.37]
[0.54, 0.37, -0.46, 0.6]
[0.54, -0.37, -0.46, -0.6]
[0.46, -0.6, 0.54, 0.37]

Verificação (A reconstruída):
[5, 4, 2, 1]
[4, 5, 3, 2]
[2, 3, 5, 4]
[1, 2, 4, 5]
